### ISSUE TITLE
Document github workflow

### ISSUE THREAD

**Issue by ffagerho** [TheSoftwareFactory/lokki#1]
This means documenting the cycle of
1. Checking out a lokki repository.
2. Making local changes.
3. Submitting them as a new pull request.
4. Doing code review.
5. Improving or rejecting the pull request.
6. Accepting the pull request (when it's good enough).

It also means documenting how to use Travis CI to autobuild both the pull requests and the main branch.

**Comment by ffagerho** [comment]
Some initial material is on https://github.com/TheSoftwareFactory/lokki/wiki

**Comment by ffagerho** [comment]
Where's the solution? :)

**Comment by Kauhsa** [comment]
Right, sorry :-)

Solution is  this: https://github.com/TheSoftwareFactory/lokki#workflow – we felt that the process described in the guide at GitHub is essentially identical to what we're using, so might as well link there and put our own additions in top of that. The link could probably link directly to the "Contributing to a Project" section of the guide, though.

We disabled the wiki in favor of README.md + potential other .md files in the repository – this is because you can't make commits (well, technically you can, but they're very hidden in GitHub) or pull requests against the wiki.

We didn't put really any info about using Travis CI as described in the issue, though, which might have been an oversight. Not that there's much to tell about the usage of Travis, since the point of it is to work automatically without you having to do anything. Only thing is to make sure that the build passes before you're merging – which was mentioned. Although I do think we're quite light on details :-)
